baseurl = "https://www.notyourlanguage.com/"
languageCode = "en-GB"
ignoreFiles = [ "\\.scss" ]
title = "Not Your Language"
theme="site-theme"

[outputs]
	home = ["HTML", "RSS", "JSON"]

[params]
	name = "Not Your Language"
	description = "You are not a programming language."
	bio = "John Darrington"
	author = "John Darrington"
	enableRSS = false
	enableDisqus = false
	disqusShortname = "notyourlanguage"

[social]
	rss-squared = "/index.xml"
	github-squared = "https://github.com/dnoberon"
