baseurl = "https://notyourlanguage.com/"
languageCode = "en-GB"
ignoreFiles = [ "\\.scss" ]
title = "GolangCode"
theme="site-theme"

[outputs]
	home = ["HTML", "RSS", "JSON"]

[params]
	name = "Not Your Language"
	description = "A Library of Go Snippets"
	bio = "John Darrington"
	author = "John Darrington"
	enableRSS = true
	enableDisqus = false
	disqusShortname = "notyourlanguage"

[social]
	rss-squared = "/index.xml"
	github-squared = "https://github.com/dnoberon"